# Generated by Django 3.0.5 on 2020-04-30 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Family_Code', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZoneName', models.CharField(max_length=200, null=True)),
                ('ZoneCode', models.CharField(max_length=200, null=True)),
                ('Family_Code', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='WatchUser_EntryUser.FamilyCode')),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zone_Name', models.CharField(max_length=200, null=True)),
                ('Relation_With_HeadPerson', models.CharField(choices=[(0, '--------'), (1, 'Daughter'), (2, 'Wife'), (3, 'Husband'), (4, 'Daughter-In-Law'), (5, 'Son-In-Law'), (6, 'Father'), (7, 'Mother'), (8, 'Grand-Father'), (9, 'Grand-Mother'), (10, 'Father-In-Law'), (11, 'Mother-In-Law'), (12, 'Son'), (13, 'HeadPerson')], default=' ', max_length=200, null=True)),
                ('Father_Name', models.CharField(max_length=200, null=True)),
                ('GrandFather_Name', models.CharField(help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=200, null=True)),
                ('Mother_Name', models.CharField(help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=200, null=True)),
                ('Member_Name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[(1, 'male'), (2, 'female'), (3, 'not specified')], default=' ', max_length=200, null=True)),
                ('Age', models.IntegerField(default='0', null=True)),
                ('MaritalStatus', models.CharField(choices=[(1, 'UnMarried'), (2, 'Married')], default=' ', max_length=200, null=True)),
                ('Address', models.TextField(max_length=400, null=True)),
                ('CURRENT_CITY', models.CharField(max_length=200, null=True)),
                ('CITY_PINCODE', models.IntegerField(null=True)),
                ('Phone_NO', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Image_Field', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('Date', models.DateTimeField(null=True)),
                ('Family_Code', models.ForeignKey(help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='WatchUser_EntryUser.FamilyCode')),
                ('Zone_Code', models.ManyToManyField(max_length=50, null=True, to='WatchUser_EntryUser.ZoneCode')),
            ],
        ),
        migrations.CreateModel(
            name='HeadPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zone_Name', models.CharField(max_length=200, null=True)),
                ('Native_City', models.CharField(max_length=70, null=True)),
                ('HeadPerson_Of_Family', models.CharField(blank=True, help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=300)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female'), (3, 'not specified')], default=' ', max_length=200)),
                ('Age', models.IntegerField(default='0', null=True)),
                ('CURRENT_CITY', models.CharField(max_length=200, null=True)),
                ('Phone_NO', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Family_Code', models.OneToOneField(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='WatchUser_EntryUser.FamilyCode')),
                ('Zone_Code', models.ManyToManyField(max_length=50, null=True, to='WatchUser_EntryUser.ZoneCode')),
            ],
        ),
        migrations.CreateModel(
            name='FeMale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zone_Name', models.CharField(max_length=200, null=True)),
                ('Native_City', models.CharField(max_length=70, null=True)),
                ('HeadPerson_Of_Family', models.CharField(help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=300, null=True)),
                ('Relation_With_HeadPerson', models.CharField(choices=[(0, '--------'), (1, 'Daughter'), (2, 'Wife'), (3, 'Husband'), (4, 'Daughter-In-Law'), (5, 'Son-In-Law'), (6, 'Father'), (7, 'Mother'), (8, 'Grand-Father'), (9, 'Grand-Mother'), (10, 'Father-In-Law'), (11, 'Mother-In-Law'), (12, 'Son'), (13, 'HeadPerson')], default=' ', max_length=200, null=True)),
                ('Father_Name', models.CharField(max_length=200, null=True)),
                ('GrandFather_Name', models.CharField(help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=200, null=True)),
                ('Mother_Name', models.CharField(help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=200, null=True)),
                ('Member_Name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[(1, 'male'), (2, 'female'), (3, 'not specified')], default=' ', max_length=200, null=True)),
                ('Age', models.IntegerField(default='0', null=True)),
                ('MaritalStatus', models.CharField(choices=[(1, 'UnMarried'), (2, 'Married')], default=' ', max_length=200, null=True)),
                ('Address', models.TextField(max_length=400, null=True)),
                ('CURRENT_CITY', models.CharField(max_length=200, null=True)),
                ('CITY_PINCODE', models.IntegerField(null=True)),
                ('Phone_NO', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Image_Field', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('Date', models.DateTimeField(null=True)),
                ('Family_Code', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='WatchUser_EntryUser.FamilyCode')),
                ('Zone_Code', models.ManyToManyField(max_length=50, null=True, to='WatchUser_EntryUser.ZoneCode')),
            ],
        ),
    ]
