# Generated by Django 3.0.5 on 2020-05-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashbord', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsAndEventsBlog',
        ),
    ]
