# Generated by Django 3.0.5 on 2020-05-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandeventsblog',
            name='NewsBlogNews',
            field=models.CharField(max_length=10000),
        ),
    ]
