# Generated by Django 3.0.5 on 2020-05-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20200531_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandeventsblog',
            name='BlogId',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
