# Generated by Django 3.0.5 on 2020-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrimonyUserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Cast', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('HeadPerson', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
                ('Study_Details', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=60)),
                ('Confirm_Pass', models.CharField(max_length=60)),
                ('DOB', models.DateField()),
                ('Age', models.CharField(choices=[(0, '18 to 20'), (1, '20 to 25'), (2, '26 to 30'), (3, '31 to 35'), (4, '36 to 40'), (5, '41 to 45'), (6, '45 to 50'), (7, '50 to 55'), (8, '55 to 60')], default=' ', max_length=200)),
                ('Father_PhoneNo', models.IntegerField()),
                ('Height', models.CharField(max_length=30)),
                ('Weight', models.CharField(max_length=30)),
                ('Gender', models.CharField(choices=[(0, 'Male'), (1, 'FeMale')], default=' ', max_length=30)),
                ('Looking_For', models.CharField(choices=[(0, 'Groom'), (1, 'Bride')], default=' ', max_length=30)),
                ('Hobbies', models.CharField(max_length=300)),
                ('Native_City', models.CharField(max_length=300)),
                ('Current_City', models.CharField(max_length=300)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
