# Generated by Django 3.0.5 on 2020-05-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matrimony', '0003_auto_20200504_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyuserreg',
            name='Confirm_Pass',
        ),
    ]
