# Generated by Django 3.0.5 on 2020-05-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('F_Code', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Zone_Name', models.CharField(max_length=200, null=True)),
                ('Native_City', models.CharField(max_length=70, null=True)),
                ('Mosad_City', models.CharField(max_length=70, null=True)),
                ('Father_Name', models.CharField(max_length=200, null=True)),
                ('GrandFather_Name', models.CharField(help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=200, null=True)),
                ('Mother_Name', models.CharField(help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=200, null=True)),
                ('HeadPerson_Of_Family', models.CharField(blank=True, help_text='Please use the following format: <em>SurName- FirstName- LastName-</em>.', max_length=300)),
                ('gender', models.CharField(blank=True, default=' ', max_length=200)),
                ('CURRENT_CITY', models.CharField(max_length=200, null=True)),
                ('Phone_NO_Office', models.CharField(max_length=200, null=True)),
                ('Phone_NO_Home', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('profile_image', models.FileField(upload_to='')),
                ('Address', models.TextField()),
                ('Town', models.CharField(max_length=200, null=True)),
                ('Taluko', models.CharField(max_length=200, null=True)),
                ('District', models.CharField(max_length=200, null=True)),
                ('CITY_PINCODE', models.CharField(max_length=200, null=True)),
                ('F_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserEntry.FamilyCode')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('M_F_Code', models.CharField(max_length=300, null=True)),
                ('M_Name', models.CharField(max_length=200, null=True)),
                ('M_Relation_To_Head', models.CharField(max_length=300, null=True)),
                ('M_BOD', models.CharField(max_length=300, null=True)),
                ('M_Study_Qualifications', models.CharField(max_length=300, null=True)),
                ('M_Profession', models.CharField(max_length=300, null=True)),
                ('M_Marital_Status', models.CharField(max_length=300, null=True)),
                ('M_Blood_Group', models.CharField(max_length=300, null=True)),
                ('M_Phone_NO', models.CharField(max_length=200, null=True)),
                ('M_Sex', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHeadFamilyMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserEntry.FamilyHead')),
                ('family_M_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserEntry.FamilyMember')),
            ],
        ),
    ]
