# Generated by Django 3.0.5 on 2020-05-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserEntry', '0002_auto_20200523_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='profile_image',
            field=models.ImageField(upload_to='media/media/images'),
        ),
    ]
