# Generated by Django 3.0.5 on 2020-05-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserEntry', '0004_auto_20200523_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='profile_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
