# Generated by Django 3.0.5 on 2020-05-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserEntry', '0005_auto_20200523_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='profile_image',
            field=models.FileField(upload_to='media'),
        ),
    ]
