# Generated by Django 3.0.5 on 2020-05-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserEntry', '0006_auto_20200524_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='profile_image',
            field=models.FileField(upload_to='static/UserImage'),
        ),
    ]
