# Generated by Django 3.0.5 on 2020-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserEntry', '0008_auto_20200524_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='profile_image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
