# Generated by Django 3.0.5 on 2020-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserEntry', '0009_auto_20200524_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='F_Code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
