# Generated by Django 3.0.5 on 2020-05-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserEntry', '0010_auto_20200526_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhead',
            name='CURRENT_CITY',
        ),
        migrations.RemoveField(
            model_name='familyhead',
            name='gender',
        ),
    ]
