# Generated by Django 3.0.5 on 2020-05-29 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserEntry', '0011_auto_20200526_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='M_BOD',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
