# Generated by Django 3.0.5 on 2020-05-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Id', models.CharField(max_length=200, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MagazineUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Magazine_Cover_Page', models.ImageField(upload_to='magazine/thumbnilimages')),
                ('Magazine_Cover_Title', models.CharField(max_length=500)),
                ('Magazine_Link', models.CharField(max_length=500, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Cover_Page', models.ImageField(upload_to='EventCoverImages')),
                ('Event_Cover_Title', models.CharField(max_length=500)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Event_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magazine.EventCode')),
            ],
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Image', models.ImageField(upload_to='PhotoS')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Event_Id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Magazine.EventCode')),
            ],
        ),
    ]
