# Generated by Django 3.0.5 on 2020-05-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='Event_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magazine.EventCode'),
        ),
    ]
