# Generated by Django 3.0.5 on 2020-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0002_auto_20200530_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimages',
            name='Re_Enter_Id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventsection',
            name='Re_Enter_Id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
